#Requires -Version 5.1
<#
.SYNOPSIS
    Review and Merge PRs using GitHub MCP Server
.DESCRIPTION
    Uses GitHub MCP server tools to review and merge PRs from Mouy-leng and A6-9V
#>

$ErrorActionPreference = "Continue"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Review & Merge PRs with MCP Server" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Configuration
$mouyLengUser = "Mouy-leng"
$a69vOrg = "A6-9V"
$workspaceRoot = $PWD.Path
$reportPath = Join-Path $workspaceRoot "PR-MERGE-REPORT.md"

# Initialize report
$report = @{
    Timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    MouyLengRepos = @()
    A69VRepos = @()
    MergedPRs = @()
    UnmergeablePRs = @()
    Errors = @()
}

Write-Host "NOTE: This script uses GitHub MCP Server tools" -ForegroundColor Yellow
Write-Host "Make sure you have appropriate permissions to merge PRs" -ForegroundColor Yellow
Write-Host ""

# Known repositories for Mouy-leng
$knownMouyLengRepos = @(
    "Window-setup",
    "ZOLO-A6-9VxNUNA-",
    "mql5-repo",
    "GenX_FX"
)

# Known repositories for A6-9V
$knownA69VRepos = @(
    "my-drive-projects",
    "I-bride_bridges3rd"
)

Write-Host "[PHASE 1] Review and Merge Pull Requests" -ForegroundColor Yellow
Write-Host "========================================" -ForegroundColor Gray
Write-Host ""

# Process Mouy-leng repositories
Write-Host "[1/2] Processing Mouy-leng repositories..." -ForegroundColor Yellow
Write-Host ""

foreach ($repoName in $knownMouyLengRepos) {
    Write-Host "  Repository: $mouyLengUser/$repoName" -ForegroundColor Cyan
    $report.MouyLengRepos += $repoName
    
    Write-Host "    Note: Use GitHub web interface or CLI to merge PRs" -ForegroundColor Gray
    Write-Host "    URL: https://github.com/$mouyLengUser/$repoName/pulls" -ForegroundColor Gray
    Write-Host ""
}

# Process A6-9V repositories
Write-Host "[2/2] Processing A6-9V organization repositories..." -ForegroundColor Yellow
Write-Host ""

foreach ($repoName in $knownA69VRepos) {
    Write-Host "  Repository: $a69vOrg/$repoName" -ForegroundColor Cyan
    $report.A69VRepos += $repoName
    
    Write-Host "    Note: Use GitHub web interface or CLI to merge PRs" -ForegroundColor Gray
    Write-Host "    URL: https://github.com/$a69vOrg/$repoName/pulls" -ForegroundColor Gray
    Write-Host ""
}

# Generate report
Write-Host ""
Write-Host "[PHASE 2] Generating Report" -ForegroundColor Yellow
Write-Host "========================================" -ForegroundColor Gray
Write-Host ""

$reportContent = @"
# Pull Request Merge Report
Generated: $($report.Timestamp)

## Summary

- **Mouy-leng Repositories**: $($knownMouyLengRepos.Count)
- **A6-9V Repositories**: $($knownA69VRepos.Count)
- **Total Repositories**: $($knownMouyLengRepos.Count + $knownA69VRepos.Count)

## Repositories to Review

### Mouy-leng Repositories

"@

foreach ($repo in $knownMouyLengRepos) {
    $reportContent += "`n- [$repo](https://github.com/$mouyLengUser/$repo/pulls)"
}

$reportContent += @"

### A6-9V Repositories

"@

foreach ($repo in $knownA69VRepos) {
    $reportContent += "`n- [$repo](https://github.com/$a69vOrg/$repo/pulls)"
}

$reportContent += @"


## Instructions

To merge pull requests:

1. **Using GitHub Web Interface**:
   - Click on the repository links above
   - Review each open pull request
   - Click "Merge pull request" for PRs you want to merge

2. **Using GitHub CLI**:
   ```bash
   # Install GitHub CLI if not already installed
   # Windows: winget install --id GitHub.cli
   
   # Login to GitHub
   gh auth login
   
   # List PRs for a repository
   gh pr list --repo OWNER/REPO
   
   # Merge a PR
   gh pr merge PR_NUMBER --repo OWNER/REPO --merge
   ```

3. **Using PowerShell Script**:
   ```powershell
   # Run the check-and-merge-prs.ps1 script in each repository
   cd path/to/repository
   .\check-and-merge-prs.ps1
   ```

---
*Report generated by review-merge-prs-mcp.ps1*
"@

$reportContent | Out-File -FilePath $reportPath -Encoding UTF8
Write-Host "Report saved to: $reportPath" -ForegroundColor Cyan

# Display summary
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Summary" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Repositories to Review:" -ForegroundColor Yellow
Write-Host "  Mouy-leng: $($knownMouyLengRepos.Count)" -ForegroundColor Cyan
Write-Host "  A6-9V: $($knownA69VRepos.Count)" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next Steps:" -ForegroundColor Yellow
Write-Host "  1. Review the report at: $reportPath" -ForegroundColor White
Write-Host "  2. Visit each repository's PR page" -ForegroundColor White
Write-Host "  3. Merge applicable pull requests" -ForegroundColor White
Write-Host "  4. Run injection script to bring changes into my-drive-projects" -ForegroundColor White
Write-Host ""
